name: MobWalk
main: org.jm.spigotmc.mobwalk.MobWalk
version: 1.0
author: SwiftLee
description: No desc.

commands:
  setmob:
    usage: /<command>
    description: Used to summon an entity that walks to the location you are currently looking at.